# Generated by Django 5.2.4 on 2025-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='objet',
            field=models.CharField(max_length=255),
        ),
    ]
