# Generated by Django 5.2.4 on 2025-07-09 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv_app', '0005_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=6)),
                ('participants', models.ManyToManyField(blank=True, related_name='ateliers_inscrits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
