# Generated by Django 5.2.3 on 2025-07-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv_app', '0006_atelier'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='duree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atelier',
            name='lieu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
