# Generated by Django 5.2.3 on 2025-07-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv_app', '0007_atelier_duree_atelier_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ateliers/'),
        ),
    ]
