# Generated by Django 5.2.4 on 2025-07-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv_app', '0011_indisponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indisponibilite',
            name='type',
            field=models.CharField(choices=[('jour', 'Jour entier'), ('creneau', 'Créneau précis')], max_length=10),
        ),
    ]
