# Generated by Django 5.2.4 on 2025-07-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv_app', '0012_message_lu_alter_indisponibilite_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='nombre_maximal',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='tarif',
            field=models.PositiveIntegerField(),
        ),
    ]
