# Generated by Django 5.2.4 on 2025-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv_app', '0016_profile_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.AddField(
            model_name='temoinage',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
